### ISSUE TITLE
allow for naming by number instead of date

### ISSUE THREAD

**Issue by ianstormtaylor** [blakeembrey/node-immigration#3]
Hey Blake, was gonna open a few issues just to hear your thoughts. Hopefully I can figure out Typescript and add PRs for them ;)

First one is, wondering what your take would be on allowing `create` to be invoked with `--numeric` or similar flag, so that instead of `20160316194212-` it would be `01-`, `02-`, ...

As far as the sorting would go, it would still make things ordered properly, so I think most pieces of the code would not need to change at all.

**Comment by blakeembrey** [comment]
Happy to, you'll just need to rename if you hit 100 ;) Other than that, the module would still work identically.
